package hibernate.pojo;
// Generated 3 Jun, 2015 5:12:49 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TblLinks generated by hbm2java
 */
public class TblLinks  implements java.io.Serializable {


     private BigDecimal ILid;
     private TblEpos tblEposITo;
     private TblEpos tblEposIFrom;
     private TblPlant tblPlant;
     private BigDecimal NTimediffInMin;

    public TblLinks() {
    }

	
    public TblLinks(BigDecimal ILid, TblPlant tblPlant) {
        this.ILid = ILid;
        this.tblPlant = tblPlant;
    }
    public TblLinks(BigDecimal ILid, TblEpos tblEposByITo, TblEpos tblEposByIFrom, TblPlant tblPlant, BigDecimal NTimediffInMin) {
       this.ILid = ILid;
       this.tblEposITo = tblEposByITo;
       this.tblEposIFrom = tblEposByIFrom;
       this.tblPlant = tblPlant;
       this.NTimediffInMin = NTimediffInMin;
    }
   
    public BigDecimal getILid() {
        return this.ILid;
    }
    
    public void setILid(BigDecimal ILid) {
        this.ILid = ILid;
    }
    public TblEpos getTblEposITo() {
        return this.tblEposITo;
    }
    
    public void setTblEposITo(TblEpos tblEposByITo) {
        this.tblEposITo = tblEposByITo;
    }
    public TblEpos getTblEposIFrom() {
        return this.tblEposIFrom;
    }
    
    public void setTblEposIFrom(TblEpos tblEposByIFrom) {
        this.tblEposIFrom = tblEposByIFrom;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public BigDecimal getNTimediffInMin() {
        return this.NTimediffInMin;
    }
    
    public void setNTimediffInMin(BigDecimal NTimediffInMin) {
        this.NTimediffInMin = NTimediffInMin;
    }




}


