package hibernate.pojo;
// Generated Jan 22, 2016 12:28:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TblType generated by hbm2java
 */
public class TblType  implements java.io.Serializable, Comparable<TblType> {


     private BigDecimal ITypeId;
     private TblPlant tblPlant;
     private String TName;

    public TblType() {
    }

	
    public TblType(BigDecimal ITypeId, TblPlant tblPlant) {
        this.ITypeId = ITypeId;
        this.tblPlant = tblPlant;
    }
    public TblType(BigDecimal ITypeId, TblPlant tblPlant, String TName) {
       this.ITypeId = ITypeId;
       this.tblPlant = tblPlant;
       this.TName = TName;
    }
   
    public BigDecimal getITypeId() {
        return this.ITypeId;
    }
    
    public void setITypeId(BigDecimal ITypeId) {
        this.ITypeId = ITypeId;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public String getTName() {
        return this.TName;
    }
    
    public void setTName(String TName) {
        this.TName = TName;
    }

    public int compareTo(TblType t)
    {
        return ITypeId.intValue() - t.getITypeId().intValue();
    }
}


